(()=>{'use strict';
const D=window.GAME_DATA; let state;
const $=s=>document.querySelector(s); const logEl=$('#log');
function clone(x){return JSON.parse(JSON.stringify(x))} function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function addLog(t){let d=document.createElement('div');d.textContent=t;logEl.prepend(d)}
function hero(id){return state.heroes.find(x=>x.id===id)} function selectedEnemy(){return state.enemies.find(x=>x.id===state.selectedEnemy&&x.hp>0)}
function reset(){state={round:1,phase:'player',heroes:clone(D.heroes).map(h=>({...h,maxHp:h.hp,block:0,used:false,rage:0,aim:false,down:false})),enemies:clone(D.enemies).map(e=>({...e,maxHp:e.hp,block:0,bleed:0})),deck:shuffle(clone(D.cards)),hand:[],discard:[],selectedEnemy:null};logEl.innerHTML='';draw(5);addLog('Encounter begins.');render()}
function draw(n){for(let i=0;i<n;i++){if(!state.deck.length&&state.discard.length){state.deck=shuffle(state.discard.splice(0));addLog('Discard shuffled into deck.')}if(state.deck.length)state.hand.push(state.deck.pop())}}
function livingEnemies(){return state.enemies.filter(e=>e.hp>0)} function livingHeroes(){return state.heroes.filter(h=>!h.down)}
function crit(h,forced=false){if(h.id!=='archer')return false;if(forced||h.aim){h.aim=false;return true}return Math.random()<.5}
function damageEnemy(e,n,opts={}){if(!e)return false;let dmg=n;if(!opts.ignoreBlock&&e.block){let b=Math.min(e.block,dmg);e.block-=b;dmg-=b}e.hp=Math.max(0,e.hp-dmg);addLog(`${e.name} takes ${dmg} damage.`);if(e.hp===0)addLog(`${e.name} is defeated.`);return e.hp===0}
function healHero(h,n){if(!h||h.down)return;let old=h.hp;h.hp=Math.min(h.maxHp,h.hp+n);addLog(`${h.name} heals ${h.hp-old}.`)}
function chooseLowest(){return livingHeroes().sort((a,b)=>(a.hp/a.maxHp)-(b.hp/b.maxHp))[0]}
function targetFor(range){let e=selectedEnemy()||livingEnemies()[0];if(!e)return null;return e}
function useBasic(id){if(state.phase!=='player')return;let h=hero(id);if(h.used||h.down)return;if(h.basic.type==='heal'){let t=chooseLowest();healHero(t,h.basic.amount);if(t.id!==h.id)healHero(h,1)}else{let e=targetFor(h.basic.range);if(!e)return;let d=h.basic.amount;if(h.id==='archer'&&crit(h)){d+=1;addLog('Archer critically strikes!')}let killed=damageEnemy(e,d);if(killed&&h.id==='warrior')h.rage++}h.used=true;render();checkEnd()}
function playCard(id){if(state.phase!=='player')return;let ix=state.hand.findIndex(c=>c.id===id);if(ix<0)return;let c=state.hand[ix],h=hero(c.hero);if(h.down)return;if(c.timing!=='Quick'&&c.timing!=='Reaction'&&h.used)return;let e=targetFor(c.range||'ranged');
 if(c.effect==='aim'){h.aim=true;draw(1);addLog('Archer takes aim.')}
 else if(c.effect==='focused'){if(!e)return;let isCrit=crit(h),d=c.amount+(isCrit?2:0);if(isCrit)addLog('Focused Shot critically strikes!');damageEnemy(e,d)}
 else if(c.effect==='pierce'){if(!e)return;let isCrit=crit(h),k=damageEnemy(e,c.amount,{ignoreBlock:true});if(isCrit&&e.hp>0){e.bleed++;addLog(`${e.name} gains Bleed.`)}}
 else if(c.effect==='multi'){let count=crit(h)?3:2;livingEnemies().slice(0,count).forEach(x=>damageEnemy(x,c.amount))}
 else if(c.effect==='damage'){if(!e)return;let killed=damageEnemy(e,c.amount);if(killed&&h.id==='warrior')h.rage++}
 else if(c.effect==='selfHeal'){healHero(h,c.amount)}
 else if(c.effect==='heal'||c.effect==='quickHeal'){let t=chooseLowest();healHero(t,c.amount);if(h.id==='cleric'&&t.id!==h.id)healHero(h,1)}
 else if(c.effect==='ready'){let t=state.heroes.find(x=>x.id!==h.id&&x.used&&!x.down);if(t){t.used=false;addLog(`${t.name} is readied.`)}draw(1)}
 else if(c.effect==='reactionCounter'){addLog('Counter Strike is a Reaction; keep it in hand for the enemy phase.');return}
 if(c.timing==='Action')h.used=true;state.hand.splice(ix,1);state.discard.push(c);render();checkEnd()}
function hasCounter(){return state.hand.find(c=>c.effect==='reactionCounter')}
function enemyAttack(e){let candidates;if(e.range==='ranged'){let back=livingHeroes().filter(h=>h.position==='back');candidates=back.length?back:livingHeroes()}else{let front=livingHeroes().filter(h=>h.position==='front');candidates=front.length?front:livingHeroes()}if(!candidates.length)return;let t=candidates[Math.floor(Math.random()*candidates.length)],d=e.attack;
 let counter=t.id==='warrior'?hasCounter():null;if(counter){d=Math.max(0,d-1);damageEnemy(e,2);state.hand.splice(state.hand.indexOf(counter),1);state.discard.push(counter);addLog('Warrior uses Counter Strike!')}
 if(t.block){let b=Math.min(t.block,d);t.block-=b;d-=b}t.hp=Math.max(0,t.hp-d);addLog(`${e.name} attacks ${t.name} for ${d}.`);if(t.hp===0){t.down=true;addLog(`${t.name} is downed.`)}}
function enemyPhase(){if(state.phase!=='player'||!livingEnemies().length)return;state.phase='enemy';render();livingEnemies().forEach(e=>{if(e.bleed){damageEnemy(e,e.bleed);if(e.hp===0)return}enemyAttack(e)});if(!livingHeroes().length){render();addLog('Defeat.');return}state.round++;state.phase='player';state.heroes.forEach(h=>{if(!h.down){h.used=false;h.block=0}});draw(3);addLog(`Round ${state.round} begins.`);render();checkEnd()}
function checkEnd(){if(!livingEnemies().length){state.phase='victory';addLog('Victory!');render()}}
function unitHTML(u,enemy=false){let pct=Math.max(0,u.hp/u.maxHp*100);return `<div class="unit ${enemy?'enemy':''} ${state.selectedEnemy===u.id?'selected':''} ${u.used?'exhausted':''} ${u.down?'down':''}" ${enemy&&u.hp>0?`data-enemy="${u.id}"`:''}><div class="unit-head"><h4>${u.name}</h4><span>${enemy?'ATK '+u.attack:(u.used?'Exhausted':'Ready')}</span></div><div class="bar"><span style="width:${pct}%"></span></div><div class="stats"><span>HP ${u.hp}/${u.maxHp}</span><span>${u.block?'Block '+u.block:''}${u.rage?' Rage '+u.rage:''}</span></div>${u.bleed?`<div class="status">Bleed ${u.bleed}</div>`:''}<div class="hint">${u.text||u.passive||''}</div>${!enemy&&!u.down?`<div class="unit-actions"><button data-basic="${u.id}" ${u.used?'disabled':''}>${u.basic.name}</button></div>`:''}</div>`}
function render(){ $('#phaseLabel').textContent=`Round ${state.round} - ${state.phase==='player'?'Player Phase':state.phase==='enemy'?'Enemy Phase':'Victory'}`;$('#deckCount').textContent=state.deck.length;$('#discardCount').textContent=state.discard.length;$('#enemyLane').innerHTML=state.enemies.map(e=>unitHTML(e,true)).join('');$('#frontline').innerHTML=state.heroes.filter(h=>h.position==='front').map(h=>unitHTML(h)).join('');$('#backline').innerHTML=state.heroes.filter(h=>h.position==='back').map(h=>unitHTML(h)).join('');$('#hand').innerHTML=state.hand.map(c=>{let h=hero(c.hero),disabled=(c.timing==='Action'&&h.used)||h.down||c.timing==='Reaction';return `<div class="game-card ${disabled?'disabled':''}" data-card="${c.id}"><div><span class="tag ${c.timing==='Quick'?'quick':c.timing==='Reaction'?'reaction':''}">${c.timing}</span><span class="tag">${h.name}</span></div><h4>${c.name}</h4><p>${c.text}</p>${c.timing==='Reaction'?'<div class="hint">Automatically triggers when valid.</div>':''}</div>`}).join('');$('#endPhaseBtn').disabled=state.phase!=='player';bind()}
function bind(){document.querySelectorAll('[data-enemy]').forEach(x=>x.onclick=()=>{state.selectedEnemy=x.dataset.enemy;render()});document.querySelectorAll('[data-basic]').forEach(x=>x.onclick=()=>useBasic(x.dataset.basic));document.querySelectorAll('[data-card]').forEach(x=>x.onclick=()=>{let c=state.hand.find(c=>c.id===x.dataset.card);if(c&&c.timing!=='Reaction')playCard(c.id)})}
$('#endPhaseBtn').onclick=enemyPhase;$('#restartBtn').onclick=reset;reset();
})();
