(()=>{'use strict';
const D=window.GAME_DATA; const HAND_LIMIT=4; let state;
const $=s=>document.querySelector(s); const logEl=$('#log');
function clone(x){return JSON.parse(JSON.stringify(x))}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function addLog(t){const d=document.createElement('div');d.textContent=t;logEl.prepend(d)}
function hero(id){return state.heroes.find(x=>x.id===id)}
function enemy(id){return state.enemies.find(x=>x.id===id)}
function livingEnemies(){return state.enemies.filter(e=>e.hp>0)}
function livingHeroes(){return state.heroes.filter(h=>!h.down)}
function reset(){state={round:1,phase:'player',heroes:clone(D.heroes).map(h=>({...h,maxHp:h.hp,block:0,used:false,rage:0,aim:false,down:false})),enemies:clone(D.enemies).map(e=>({...e,maxHp:e.hp,block:0,bleed:0})),deck:shuffle(clone(D.cards)),hand:[],discard:[],pending:null};logEl.innerHTML='';draw(HAND_LIMIT);addLog('Encounter begins.');render()}
function draw(n){let drawn=0;for(let i=0;i<n;i++){if(state.hand.length>=HAND_LIMIT){if(i===0)addLog(`Hand is full (${HAND_LIMIT}).`);break}if(!state.deck.length&&state.discard.length){state.deck=shuffle(state.discard.splice(0));addLog('Discard shuffled into deck.')}if(!state.deck.length)break;state.hand.push(state.deck.pop());drawn++}return drawn}
function crit(h,forced=false){if(h.id!=='archer')return false;if(forced||h.aim){h.aim=false;return true}return Math.random()<.5}
function damageEnemy(e,n,opts={}){if(!e)return false;let dmg=n;if(!opts.ignoreBlock&&e.block){const b=Math.min(e.block,dmg);e.block-=b;dmg-=b}e.hp=Math.max(0,e.hp-dmg);addLog(`${e.name} takes ${dmg} damage.`);if(e.hp===0)addLog(`${e.name} is defeated.`);return e.hp===0}
function healHero(h,n){if(!h||h.down)return;const old=h.hp;h.hp=Math.min(h.maxHp,h.hp+n);addLog(`${h.name} heals ${h.hp-old}.`)}
function canTargetEnemy(h,range,e,isBasic=false){if(!e||e.hp<=0)return false;if(range!=='melee')return true;const sameLane=state.enemies.some(x=>x.hp>0); // v0.2 currently has one player lane
if(sameLane)return true;return isBasic}
function clearPending(){state.pending=null}
function beginBasic(id){if(state.phase!=='player')return;const h=hero(id);if(!h||h.used||h.down)return;if(h.basic.type==='heal')setPending({source:'basic',heroId:id,targetType:'ally',prompt:`Choose an ally for ${h.basic.name}.`});else setPending({source:'basic',heroId:id,targetType:'enemy',range:h.basic.range,prompt:`Choose an enemy for ${h.basic.name}.`})}
function beginCard(id){if(state.phase!=='player')return;const ix=state.hand.findIndex(c=>c.id===id);if(ix<0)return;const c=state.hand[ix],h=hero(c.hero);if(h.down)return;if(c.timing==='Reaction')return;if(c.timing==='Action'&&h.used)return;
 if(c.effect==='aim'||c.effect==='selfHeal'||c.effect==='multi'){resolveCard(c,null);return}
 if(c.effect==='heal'||c.effect==='quickHeal'){setPending({source:'card',cardId:id,heroId:h.id,targetType:'ally',prompt:`Choose an ally for ${c.name}.`});return}
 if(c.effect==='ready'){const valid=state.heroes.filter(x=>x.id!==h.id&&x.used&&!x.down);if(!valid.length){addLog('No exhausted ally can be readied.');return}setPending({source:'card',cardId:id,heroId:h.id,targetType:'readyAlly',prompt:`Choose an exhausted ally for ${c.name}.`});return}
 setPending({source:'card',cardId:id,heroId:h.id,targetType:'enemy',range:c.range||'ranged',prompt:`Choose an enemy for ${c.name}.`})}
function setPending(p){state.pending=p;render()}
function selectEnemyTarget(id){if(!state.pending||state.pending.targetType!=='enemy')return;const e=enemy(id),h=hero(state.pending.heroId);if(!canTargetEnemy(h,state.pending.range,e,state.pending.source==='basic'))return;if(state.pending.source==='basic')resolveBasic(h,e);else{const c=state.hand.find(x=>x.id===state.pending.cardId);if(c)resolveCard(c,e)}}
function selectHeroTarget(id){if(!state.pending||!['ally','readyAlly'].includes(state.pending.targetType))return;const t=hero(id);if(!t||t.down)return;if(state.pending.targetType==='readyAlly'&&!t.used)return;const h=hero(state.pending.heroId);if(state.pending.source==='basic')resolveBasic(h,t);else{const c=state.hand.find(x=>x.id===state.pending.cardId);if(c)resolveCard(c,t)}}
function resolveBasic(h,target){if(!h||h.used||h.down)return;if(h.basic.type==='heal'){healHero(target,h.basic.amount);if(target.id!==h.id)healHero(h,1)}else{let d=h.basic.amount;if(h.id==='archer'&&crit(h)){d+=1;addLog('Archer critically strikes!')}const killed=damageEnemy(target,d);if(killed&&h.id==='warrior')h.rage++}h.used=true;clearPending();render();checkEnd()}
function consumeCard(c){const ix=state.hand.findIndex(x=>x.id===c.id);if(ix>=0){state.hand.splice(ix,1);state.discard.push(c)}}
function resolveCard(c,target){const h=hero(c.hero);if(!h||h.down)return;
 if(c.effect==='aim'){h.aim=true;draw(1);addLog('Archer takes aim.')}
 else if(c.effect==='focused'){const isCrit=crit(h),d=c.amount+(isCrit?2:0);if(isCrit)addLog('Focused Shot critically strikes!');damageEnemy(target,d)}
 else if(c.effect==='pierce'){const isCrit=crit(h);damageEnemy(target,c.amount,{ignoreBlock:true});if(isCrit&&target.hp>0){target.bleed++;addLog(`${target.name} gains Bleed.`)}}
 else if(c.effect==='multi'){const count=crit(h)?3:2;livingEnemies().slice(0,count).forEach(x=>damageEnemy(x,c.amount))}
 else if(c.effect==='damage'){const killed=damageEnemy(target,c.amount);if(killed&&h.id==='warrior')h.rage++}
 else if(c.effect==='selfHeal'){healHero(h,c.amount)}
 else if(c.effect==='heal'||c.effect==='quickHeal'){healHero(target,c.amount);if(h.id==='cleric'&&target.id!==h.id)healHero(h,1)}
 else if(c.effect==='ready'){target.used=false;addLog(`${target.name} is readied.`);draw(1)}
 else if(c.effect==='reactionCounter'){return}
 if(c.timing==='Action')h.used=true;consumeCard(c);clearPending();render();checkEnd()}
function hasCounter(){return state.hand.find(c=>c.effect==='reactionCounter')}
function enemyAttack(e){let candidates;if(e.range==='ranged'){const back=livingHeroes().filter(h=>h.position==='back');candidates=back.length?back:livingHeroes()}else{const front=livingHeroes().filter(h=>h.position==='front');candidates=front.length?front:livingHeroes()}if(!candidates.length)return;const t=candidates[Math.floor(Math.random()*candidates.length)];let d=e.attack;const counter=t.id==='warrior'?hasCounter():null;if(counter){d=Math.max(0,d-1);damageEnemy(e,2);consumeCard(counter);addLog('Warrior uses Counter Strike!')}if(t.block){const b=Math.min(t.block,d);t.block-=b;d-=b}t.hp=Math.max(0,t.hp-d);addLog(`${e.name} attacks ${t.name} for ${d}.`);if(t.hp===0){t.down=true;addLog(`${t.name} is downed.`)}}
function enemyPhase(){if(state.phase!=='player'||!livingEnemies().length)return;clearPending();state.phase='enemy';render();livingEnemies().forEach(e=>{if(e.bleed){damageEnemy(e,e.bleed);if(e.hp===0)return}enemyAttack(e)});if(!livingHeroes().length){render();addLog('Defeat.');return}state.round++;state.phase='player';state.heroes.forEach(h=>{if(!h.down){h.used=false;h.block=0}});draw(3);addLog(`Round ${state.round} begins.`);render();checkEnd()}
function checkEnd(){if(!livingEnemies().length){state.phase='victory';clearPending();addLog('Victory!');render()}}
function basicDescription(h){return h.basic.description||`${h.basic.name}: ${h.basic.type==='heal'?`Heal an ally for ${h.basic.amount}.`:`Deal ${h.basic.amount} ${h.basic.range==='melee'?'Melee':'Ranged'} damage.`}`}
function unitHTML(u,isEnemy=false){const pct=Math.max(0,u.hp/u.maxHp*100);let targetable=false;if(state.pending){if(isEnemy&&state.pending.targetType==='enemy')targetable=canTargetEnemy(hero(state.pending.heroId),state.pending.range,u,state.pending.source==='basic');if(!isEnemy&&state.pending.targetType==='ally')targetable=!u.down;if(!isEnemy&&state.pending.targetType==='readyAlly')targetable=!u.down&&u.used&&u.id!==state.pending.heroId}
 return `<div class="unit ${isEnemy?'enemy':''} ${u.used?'exhausted':''} ${u.down?'down':''} ${targetable?'targetable':''}" ${targetable?`${isEnemy?'data-enemy-target':'data-hero-target'}="${u.id}"`:''}><div class="unit-head"><h4>${u.name}</h4><span>${isEnemy?'ATK '+u.attack:(u.used?'Exhausted':'Ready')}</span></div><div class="bar"><span style="width:${pct}%"></span></div><div class="stats"><span>HP ${u.hp}/${u.maxHp}</span><span>${u.block?'Block '+u.block:''}${u.rage?' Rage '+u.rage:''}</span></div>${u.bleed?`<div class="status">Bleed ${u.bleed}</div>`:''}${!isEnemy?`<div class="ability"><b>Basic — ${u.basic.name}:</b> ${basicDescription(u)}</div><div class="ability"><b>Passive:</b> ${u.passive||'—'}</div>`:`<div class="hint">${u.text||''}</div>`}${!isEnemy&&!u.down?`<div class="unit-actions"><button data-basic="${u.id}" ${u.used||state.phase!=='player'?'disabled':''}>Use Basic</button></div>`:''}</div>`}
function render(){const prompt=state.pending?state.pending.prompt:'Choose a card or Basic Action.';$('#phaseLabel').textContent=`Round ${state.round} - ${state.phase==='player'?'Player Phase':state.phase==='enemy'?'Enemy Phase':'Victory'}`;$('#targetPrompt').textContent=state.phase==='player'?prompt:'';$('#deckCount').textContent=state.deck.length;$('#discardCount').textContent=state.discard.length;$('#handCount').textContent=`${state.hand.length}/${HAND_LIMIT}`;$('#enemyLane').innerHTML=state.enemies.map(e=>unitHTML(e,true)).join('');$('#frontline').innerHTML=state.heroes.filter(h=>h.position==='front').map(h=>unitHTML(h)).join('');$('#backline').innerHTML=state.heroes.filter(h=>h.position==='back').map(h=>unitHTML(h)).join('');$('#hand').innerHTML=state.hand.map(c=>{const h=hero(c.hero),disabled=(c.timing==='Action'&&h.used)||h.down||c.timing==='Reaction'||state.phase!=='player';const selected=state.pending&&state.pending.cardId===c.id;return `<button type="button" class="game-card ${disabled?'disabled':''} ${selected?'selected-card':''}" data-card="${c.id}" ${disabled?'disabled':''}><div><span class="tag ${c.timing==='Quick'?'quick':c.timing==='Reaction'?'reaction':''}">${c.timing}</span><span class="tag">${h.name}</span></div><h4>${c.name}</h4><p>${c.text}</p>${c.timing==='Reaction'?'<div class="hint">Automatically triggers when valid.</div>':''}</button>`}).join('')||'<div class="empty">No cards in hand.</div>';$('#endPhaseBtn').disabled=state.phase!=='player';$('#cancelTargetBtn').hidden=!state.pending;bind()}
function bind(){document.querySelectorAll('[data-enemy-target]').forEach(x=>x.onclick=()=>selectEnemyTarget(x.dataset.enemyTarget));document.querySelectorAll('[data-hero-target]').forEach(x=>x.onclick=()=>selectHeroTarget(x.dataset.heroTarget));document.querySelectorAll('[data-basic]').forEach(x=>x.onclick=()=>beginBasic(x.dataset.basic));document.querySelectorAll('[data-card]').forEach(x=>x.onclick=()=>beginCard(x.dataset.card))}
$('#endPhaseBtn').onclick=enemyPhase;$('#restartBtn').onclick=reset;$('#cancelTargetBtn').onclick=()=>{clearPending();render()};reset();
})();
